---
title: "Getting started"
format: 
  html:
    code-fold: true
number-sections: true
---

## What Can Be Forecast? {#sec-what-can-be-forecast}

predictability of an event or a quantity depends on several factors including:
1. how well we understand the factors that contribute to it;
2. how much data is available;
3. how similar the future is to the past;
4. whether the forecasts can affect the thing we are trying to forecast.

Often in forecasting, a key step is knowing
    when something can be forecast accurately,
    and when forecasts will be no better than tossing a coin. </br>
Good forecasts capture the genuine patterns and relationships
    which exist in the historical data,
    but do not replicate past events that will not occur again.

Many people wrongly assume that forecasts
    are not possible in a changing environment. </br>
Every environment is changing,
    and a good forecasting model captures the way in which things are changing.  
Forecasts rarely assume that the environment is unchanging. </br>
What is normally assumed is that the way in which the environment is changing
    will continue into the future. </br>
That is, a highly volatile environment will continue to be highly volatile. </br>
A forecasting model is intended to capture the way things move,
    not just where things are.

Forecasting situations vary widely in
    their time horizons,
    factors determining actual outcomes,
    types of data patterns, and
    many other aspects. </br>
Forecasting methods can be simple,
    such as using the most recent observation as a forecast
    (which is called the **naïve method**), or
    highly complex,
        such as neural nets and econometric systems of simultaneous equations. </br>
Sometimes, there will be no data available at all. </br>
**example**,
    we may wish to forecast the sales of a new product in its first year,
    but there are obviously no data to work with. </br>
    In situations like this, we use **judgmental forecasting**,
        discussed in [Chapter 6](./chapter_6__Judgmental_forecasts.qmd). </br>
The choice of method depends on
    what data are available and
    the predictability of the quantity to be forecast.


## Forecasting, Goals And Planning {#sec-forecasting-goals-planning}

business forecasting is often done poorly,
    and is frequently confused with planning and goals.  
They are three different things.

**Forecasting**
    is about predicting the future as accurately as possible,
    given all of the information available, including
        historical data and
        knowledge of any future events that might impact the forecasts.

**Goals**
    are what you would like to have happen. </br>
    Goals should be linked to forecasts and plans, but this does not always occur. </br>
    Too often, goals are set without any plan for how to achieve them,
        and no forecasts for whether they are realistic.

**Planning**
    is a response to forecasts and goals. </br>
    Planning involves determining the appropriate actions
        that are required to make your forecasts match your goals. 


Forecasting should be an integral part of the decision-making activities of management,
    as it can play an important role in many areas of a company. </br>
Modern organisations require
    short-term, medium-term and long-term forecasts,
    depending on the specific application.

**Short-term forecasts**
    are needed for the scheduling of personnel, production and transportation. </br>
    As part of the scheduling process, forecasts of demand are often also required.

**Medium-term forecasts**
    are needed to determine future resource requirements,
    in order to purchase raw materials, hire personnel, or buy machinery and equipment.

**Long-term forecasts**
    are used in strategic planning. </br>
    Such decisions must take account of
        market opportunities, environmental factors and internal resources.

An organisation needs to develop a forecasting system
    that involves several approaches to predicting uncertain events. </br>
Such forecasting systems require the development of
    expertise in identifying forecasting problems,
    applying a range of forecasting methods,
    selecting appropriate methods for each problem, and
    evaluating and refining forecasting methods over time. </br>
It is also important to have strong organisational support
    for the use of formal forecasting methods
    if they are to be used successfully.


## Determining What To Forecast {#sec-determining-what-to-forecast}

In the early stages of a forecasting project,
    decisions need to be made about what should be forecast.

also necessary to consider the forecasting horizon. </br>
Different types of models will be necessary,
    depending on what forecast horizon is most important.

How frequently are forecasts required? </br>
Forecasts that need to be produced frequently
    are better done using an automated system
    than with methods that require careful manual work.

It is worth spending time talking to the people who will use the forecasts
    to ensure that you understand their needs,
    and how the forecasts are to be used,
    before embarking on extensive work in producing the forecasts.

then necessary to find or collect the data on which the forecasts will be based. </br>
large part of a forecaster’s time can be spent
    in locating and collating the available data
    prior to developing suitable forecasting methods.


## Forecasting Data And Methods {#sec-forecasting-data-methods}

appropriate forecasting methods depend largely on what data are available.

If there are no data available,
    or if the data available are not relevant to the forecasts,
    then **qualitative forecasting methods** must be used. </br>
These methods are not purely guesswork —
    there are well-developed structured approaches
    to obtaining good forecasts without using historical data. </br>
discussed in [Chapter 6](./chapter_6__Judgmental_forecasts.qmd).


**Quantitative forecasting**
    can be applied when two conditions are satisfied:
1. numerical information about the past is available;
2. it is reasonable to assume that some aspects of the past patterns will continue into the future.

wide range of quantitative forecasting methods,
    often developed within specific disciplines for specific purposes. </br>
Each method has its own properties, accuracies, and costs
    that must be considered when choosing a specific method.

Anything that is observed sequentially over time is a time series.

When forecasting time series data,
    the aim is to estimate how the sequence of observations
    will continue into the future.

prediction intervals are a useful way of displaying the uncertainty in forecasts. </br>
if the forecasts are expected to be accurate,
    the prediction intervals are quite narrow.

simplest time series forecasting methods
    use only information on the variable to be forecast,
    and make no attempt to discover the factors that affect its behaviour.

Decomposition methods are helpful for studying
    the trend and seasonal patterns in a time series,
    discussed in [Chapter 3](./chapter_3_time_series_decomposition.qmd). </br>
Popular time series models used for forecasting include
    **exponential smoothing models** and **ARIMA models**,
    discussed in
        [Chapter 8](./chapter_8__Exponential_Smoothing.qmd) and
        [Chapter 9](./chapter_9__ARIMA_models.qmd) respectively.


### Predictor Variables And Time Series Forecasting {#sec-predictor-variables-time-series-forecasting}

**explanatory model**
    helps explain what causes the variation in electricity demand.

**time series model for forecasting**
    prediction of the future is based on past values of a variable,
    but not on external variables that may affect the system.

third type of model which combines the features of the above two models. </br>
These types of mixed models have been given various names in different disciplines. </br>
known as
    dynamic regression models,
    panel data models,
    longitudinal models,
    transfer function models, and
    linear system models (assuming that $f())$ is linear). </br>
discussed in [Chapter 10](./chapter_10__Dynamic_regression_models.qmd).

explanatory model is useful because
    it incorporates information about other variables,
    rather than only historical values of the variable to be forecast. </br>
However, there are several reasons a forecaster might select a time series model
    rather than an explanatory or mixed model. </br>
First,
    the system may not be understood,
    and even if it was understood it may be extremely difficult to measure
    the relationships that are assumed to govern its behaviour. </br>
Second,
    it is necessary to know or forecast the future values of the various predictors
    in order to be able to forecast the variable of interest,
    and this may be too difficult. </br>
Third,
    the main concern may be only to predict what will happen,
    not to know why it happens. </br>
Finally,
    the time series model may give more accurate forecasts
    than an explanatory or mixed model.

model to be used in forecasting depends on
    the resources and data available,
    the accuracy of the competing models, and
    the way in which the forecasting model is to be used.


## Some Case Studies {#sec-case-studies}


## The Basic Steps In A Forecasting Task {#sec-basic-steps-in-forecasting-task}

A forecasting task usually involves five basic steps.

**Step 1: Problem definition.**
    Often this is the most difficult part of forecasting. </br>
    Defining the problem carefully requires an understanding of the way
        the forecasts will be used,
        who requires the forecasts, and
        how the forecasting function fits
            within the organisation requiring the forecasts. </br>
    A forecaster needs to spend time talking to everyone
        who will be involved in collecting data,
        maintaining databases, and
        using the forecasts for future planning.

**Step 2: Gathering information.**
    There are always at least two kinds of information required:
        a. statistical data, and
        b. the accumulated expertise of the people who collect the data
            and use the forecasts. </br>
        Often, it will be difficult to obtain enough historical data
            to be able to fit a good statistical model. </br>
        In that case, the judgmental forecasting methods of
            [Chapter 6](./chapter_6__Judgmental_forecasts.qmd) can be used. </br>
        Occasionally, old data will be less useful
            due to structural changes in the system being forecast;
            then we may choose to use only the most recent data. </br>
        However, remember that good statistical models will handle
            evolutionary changes in the system;
            don’t throw away good data unnecessarily.

**Step 3: Preliminary (exploratory) analysis.**
    Always start by graphing the data.  
        Are there consistent patterns?  
        Is there a significant trend?  
        Is seasonality important?  
        Is there evidence of the presence of business cycles?  
        Are there any outliers in the data that need to be explained
            by those with expert knowledge?  
        How strong are the relationships among the variables available for analysis? </br>
    Various tools have been developed to help with this analysis. </br>
    These are discussed in
        [Chapter 2](./chapter_2__time_series_graphics.qmd) and
        [Chapter 3](./chapter_3_time_series_decomposition.qmd).

**Step 4: Choosing and fitting models.**
    The best model to use depends on
        the availability of historical data,
        the strength of relationships between
            the forecast variable and any explanatory variables, and
        the way in which the forecasts are to be used. </br>
    It is common to compare two or three potential models. </br>
    Each model is itself an artificial construct
        that is based on a set of assumptions (explicit and implicit)
        and usually involves one or more parameters which must be estimated
            using the known historical data. </br>
    will discuss
        regression models
            ([Chapter 7](./chapter_7__Time_series_regression_model.qmd)),
        exponential smoothing methods
            ([Chapter 8](./chapter_8__Exponential_Smoothing.qmd)),
        Box-Jenkins ARIMA models
            ([Chapter 9](./chapter_9__ARIMA_models.qmd)),
        Dynamic regression models
            ([Chapter 10](./chapter_10__Dynamic_regression_models.qmd)),
        Hierarchical forecasting
            ([Chapter 11](./chapter_11__Forecasting_hierarchical_and_grouped_time_series.qmd)), and
        several advanced methods including
            neural networks and vector autoregression
            ([Chapter 12](./chapter_12__Advanced_forecasting_methods.qmd)).

**Step 5: Using and evaluating a forecasting model.**
    Once a model has been selected and its parameters estimated,
        the model is used to make forecasts. </br>
    The performance of the model can only be properly evaluated
        after the data for the forecast period have become available. </br>
    A number of methods have been developed
        to help in assessing the accuracy of forecasts. </br>
    There are also organisational issues in using and acting on the forecasts. </br>
    A brief discussion of some of these issues is given in
        [Chapter 5](./chapter_5__The_forecaster's_toolbox.qmd). </br>
    When using a forecasting model in practice,
        numerous practical issues arise such as
            how to handle missing values and outliers, or
            how to deal with short time series. </br>
    These are discussed in
        [Chapter 13](./chapter_13__Some_practical_forecasting_issues.qmd).


## The Statistical Forecasting Perspective {#sec-statistical-forecasting-perspective}

The thing we are trying to forecast is unknown
    (or we would not be forecasting it),
    and so we can think of it as a **random variable**.

In most forecasting situations,
    the variation associated with the thing we are forecasting
    will shrink as the event approaches. </br>
In other words, the further ahead we forecast, the more uncertain we are.

can imagine many possible futures,
    each yielding a different value for the thing we wish to forecast.


When we obtain a forecast,
    we are estimating the middle of the range of possible values
    the random variable could take. </br>
Often, a forecast is accompanied by a

> **prediction interval** </br>
    giving a range of values the random variable could take
    with relatively high probability.

**example**,
    a 95% prediction interval contains a range of values
    which should include the actual future value with probability 95%.  

> ***point forecasts*** </br>
    is the average of the possible future values

will use the subscript $t$ for time. </br>
**example**,
    $y_t$ will denote the observation at time $t$. </br>

> **probability distribution** </br>
set of values that this random variable could take,
    along with their relative probabilities. </br>
In forecasting, we call this the **forecast distribution**.


When we talk about the “forecast”,
    we usually mean the average value of the forecast distribution,
    and we put a “hat” over $y$ to show this, i.e. $\hat{y}_t$,
    meaning the average of the possible values
        that $y_t$ could take given everything we know.


## Exercises


## Future Reading
